theme = "slick"
icons = "awesome5"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "networkmanager"
device_format = "{icon}{ap}"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "notify"

[[block]]
block = "time"
interval = 60
format = "%a %d.%m %R"
